image: node:12.4.0
# 定义 stages  gitlab
stages:
  - runtask
cache:
  paths:
    - node_modules/
variables:
  IS_AZURE_DEVOPS: '1'
  PLTFMFLG: 'GLC'

doSignTask:
  stage: runtask
  only:
  - master
  script: |
    npm install --only=prod
    sh task.sh
  after_script: 
    - date 
    - sh task_done.sh